sudo: false
language: python
matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7-dev
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=mypy-py2
    - python: 3.6
      env: TOXENV=mypy-py3
    - python: 3.6
      env: TOXENV=bandit
    - python: 3.6
      env: TOXENV=doc8
    - python: 3.6
      env: TOXENV=readme
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=pylint
    - python: 3.6
      env: TOXENV=flake8-tests
    - python: 3.6
      env: TOXENV=pylint-tests
    - python: 3.6
      env: TOXENV=black-check
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0; fi
    - pip install tox
script: tox
