# This workflow runs static analysis checks on pull requests.
name: static analysis

on:
  pull_request:
  push:
  # Run once a day
  schedule:
    - cron: '0 0 * * *'

jobs:
  analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        category:
          - readme
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r ci-requirements.txt
      - name: check
        env:
          TOXENV: ${{ matrix.category }}
        run: tox -- -vv
