# This workflow runs tests on pull requests.
name: tests

on:
  pull_request:
  push:
  # Run once a day
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: true
      matrix:
        platform:
          - os: ubuntu-latest
            architecture: x64
          - os: windows-latest
            architecture: x64
          # x86 builds are only meaningful for Windows
          - os: windows-latest
            architecture: x86
          - os: macos-latest
            architecture: x64
        major:
          - 3
        minor:
          - 8
          - 9
          - 10
          - 11
          - 12
        category:
          # Runs the base test environment
          - py
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.major }}.${{ matrix.minor }}'
          architecture: ${{ matrix.platform.architecture }}
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r ci-requirements.txt
      - name: run test
        env:
          TOXENV: '${{ matrix.category }}${{ matrix.major }}${{ matrix.minor }}'
        run: tox -- -vv
