# This workflow routes pull requests to the correct branch
name: pull request router

on: [pull_request]

jobs:
  send-to-develop:
    # Move any PRs to master that do *not* come from development
    if: github.base_ref == 'master' && github.head_ref != 'development'
    runs-on: ubuntu-latest
    steps:
      - name: switch
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.update({
              pull_number: context.issue.number,
              base: 'development',
              ...context.repo
            })
            github.issues.createComment({
              issue_number: context.issue.number,
              body: 'Moving target to development branch.',
              ...context.repo
            })
