# This workflow promotes pushes to development to master
name: Promote development to master

on:
  push:
    branches:
      - development

jobs:
  promote-to-master:
    name: Promote dev branch to master
    runs-on: ubuntu-latest
    steps:
      - name: promote
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: development
          PULL_REQUEST_BRANCH: master
          PULL_REQUEST_TITLE: Promote development to master
          PULL_REQUEST_BODY: |
            Automatic promotion from development to master.
